account:
  initial_cash: 1000000
  order_lot_size: 100
  short_margin_rate: 0.2
  trading_mode: long_only
  trading_rule: T+1
benchmark:
  symbol: '000300'
engine:
  enable_intraday_statistics: true
  end_date: '2023-10-31'
  frequency: minute
  intraday_update_frequency: 5
  mode: simulation
  start_date: '2023-01-01'
  strategy_name: MyStrategy
  tick_interval_seconds: 3
lifecycle:
  hooks:
    after_trading: '15:05:00'
    before_trading: 09:15:00
    broker_settle: '15:30:00'
    handle_bar: '14:55:00'
  trading_sessions:
  - - 09:30:00
    - '11:30:00'
  - - '13:00:00'
    - '15:00:00'
logging:
  buffer_size: 1000
  console_output: true
  level: INFO
matching:
  commission:
    buy_commission: 0.0002
    buy_tax: 0.0
    min_commission: 5.0
    sell_commission: 0.0002
    sell_tax: 0.001
  slippage:
    rate: 0.001
    type: fixed
report:
  auto_open: true
server:
  auto_open_browser: true
  enable: true
  port: 8050
  update_interval: 0.5
workspace:
  auto_save_interval: 1
  auto_save_mode: overwrite
  auto_save_state: false
  create_code_snapshot: true
  create_config_snapshot: true
  create_data_provider_snapshot: true
